#!/bin/bash

# Start the first process
./run_stream_editor.sh -D
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start SDS Stream-Editor: $status"
  exit $status
fi

while sleep 60; do
  ps aux |grep my_first_process |grep -q -v grep
  PROCESS_1_STATUS=$?
  # If the greps above find anything, they exit with 0 status
  # If they are not both 0, then something is wrong
  if [ $PROCESS_1_STATUS -ne 0 ]; then
    echo "One of the processes has already exited."
    exit 1
  fi
done







